BASEDIR?=$(subst /Makefiles,,$(CURDIR))
include $(BASEDIR)/Settings/hic_parameters.txt
EMPTY=
SPACE=$(EMPTY) $(EMPTY)
COMMA=$(EMPTY),$(EMPTY)
HIC_NAMES=mm9_ESC_HindIII mm9_ESC_NcoI hg19_GM12878_MboI hg19_GM12878_HindIII
MM9_NAMES=mm9_ESC_HindIII mm9_ESC_NcoI
RESOLUTIONS=1M 250K 1M 250K 50K 10K
TRANS=1 1 0 0 0 0  
HG19_CHROMS=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,X
MM9_CHROMS=1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,X
HG19_MAX=249300000
MM9_MAX=197200000
CHROMS=$(MM9_CHROMS) $(MM9_CHROMS) $(HG19_CHROMS) $(HG19_CHROMS)
NUM_PROCS?=1
ifeq ($(NUM_PROCS),1)
	MPI=$(EMPTY)
else
	MPI=mpirun -np $(NUM_PROCS)
endif

###########################################################################
all: correlations timing
###########################################################################

###########################################################################
# Find correlations between pairs of heatmaps for all resolutions and datasets
###########################################################################
correlations: $(foreach NAME,$(HIC_NAMES),$(foreach PROC,exp bin prob,$(BASEDIR)/Analysis/hifive_$(NAME)_$(PROC)_correlations.txt)) \
	$(foreach NAME,$(HIC_NAMES),$(BASEDIR)/Analysis/hicnorm_$(NAME)_correlations.txt) \
	$(foreach NAME,$(HIC_NAMES),$(BASEDIR)/Analysis/hicpipe_$(NAME)_correlations.txt) \
	$(foreach NAME,$(HIC_NAMES),$(BASEDIR)/Analysis/mb_$(NAME)_correlations.txt) \
	$(foreach NAME,$(MM9_NAMES),$(BASEDIR)/Analysis/hifive_$(NAME)_expnodist_correlations.txt) \
	$(foreach NAME,$(MM9_NAMES),$(foreach PC,1 3 6,$(BASEDIR)/Analysis/hifive_$(NAME)_binPC$(PC)_correlations.txt))

define correlation_template
$(BASEDIR)/Analysis/$3_$1%_correlations.txt:
	$(MPI) python $(BASEDIR)/Scripts/Analysis/find_hic_HM_correlations.py \
		$(BASEDIR)/Data/HiC/$2/HM/$1$$*_1M.hch $(BASEDIR)/Data/HiC/$2/HM/$1$$*_1M.hch \
		$4 10 1 $5 > $$@
	$(MPI) python $(BASEDIR)/Scripts/Analysis/find_hic_HM_correlations.py \
		$(BASEDIR)/Data/HiC/$2/HM/$1$$*_250K.hch $(BASEDIR)/Data/HiC/$2/HM/$1$$*_250K.hch \
		$4 10 1 $5 > $$@
	$(MPI) python $(BASEDIR)/Scripts/Analysis/find_hic_HM_correlations.py \
		$(BASEDIR)/Data/HiC/$2/HM/$1$$*_1M.hch $(BASEDIR)/Data/HiC/$2/HM/$1$$*_1M.hch \
		$4 10 0 $5 > $$@
	$(MPI) python $(BASEDIR)/Scripts/Analysis/find_hic_HM_correlations.py \
		$(BASEDIR)/Data/HiC/$2/HM/$1$$*_250K.hch $(BASEDIR)/Data/HiC/$2/HM/$1$$*_250K.hch \
		$4 10 0 $5 > $$@
	$(MPI) python $(BASEDIR)/Scripts/Analysis/find_hic_HM_correlations.py \
		$(BASEDIR)/Data/HiC/$2/HM/$1$$*_50K.hch $(BASEDIR)/Data/HiC/$2/HM/$1$$*_50K.hch \
		$4 10 0 $5 > $$@
	$(MPI) python $(BASEDIR)/Scripts/Analysis/find_hic_HM_correlations.py \
		$(BASEDIR)/Data/HiC/$2/HM/$1$$*_10K.hch $(BASEDIR)/Data/HiC/$2/HM/$1$$*_10K.hch \
		$4 10 0 $5 > $$@
endef
$(eval $(call correlation_template,mm9,HiFive,hifive,$(MM9_CHROMS),$(MM9_MAX)))
$(eval $(call correlation_template,hg19,HiFive,hifive,$(HG19_CHROMS),$(HG19_MAX)))
$(eval $(call correlation_template,mm9,HiCNorm,hicnorm,$(MM9_CHROMS),$(MM9_MAX)))
$(eval $(call correlation_template,hg19,HiCNorm,hicnorm,$(HG19_CHROMS),$(HG19_MAX)))
$(eval $(call correlation_template,mm9,HiCPipe,hicnorm,$(MM9_CHROMS),$(MM9_MAX)))
$(eval $(call correlation_template,hg19,HiCPipe,hicnorm,$(HG19_CHROMS),$(HG19_MAX)))
$(eval $(call correlation_template,mm9,MB,mb,$(MM9_CHROMS),$(MM9_MAX)))
$(eval $(call correlation_template,hg19,MB,mb,$(HG19_CHROMS),$(HG19_MAX)))

###########################################################################
# Run scripts to get analsyis timings and memory usage
###########################################################################
timing: setup hifive_timing hicnorm_timing hicpipe_timing hiclib_timing

hifive_timing: $(foreach N,0 1 2 3 4, $(foreach PHASE,data project project_nodist exp expKR expKRdist bin prob exp_heatmap expKR_heatmap expKRdist_heatmap bin_heatmap prob_heatmap,$(Analysis/Timing/hifive_$(PHASE)_$(N).txt)))

hicpipe_timing: $(foreach N,0 1 2 3 4, $(foreach PHASE,data binning norm heatmap,$(Analysis/Timing/hicpipe_$(PHASE)_$(N).txt)))

hicnorm_timing: $(foreach N,0 1 2 3 4, $(foreach PHASE,data norm,$(Analysis/Timing/hicnorm_$(PHASE)_$(N).txt)))

hiclib_timing: $(foreach N,0 1 2 3 4, $(foreach PHASE,mapping data norm heatmap,$(Analysis/Timing/hiclib_$(PHASE)_$(N).txt)))

define hifive_timing_template
$(BASEDIR)/Analysis/Timing/hifive_%_$1.txt:
	@mkdir -p $(BASEDIR)/Analysis/Timing
	@export BASEDIR=$(BASEDIR)
	/usr/bin/time --verbose --output=$$@ $(BASEDIR)/Scripts/Timing/hifive_$$*.sh
endef
$(foreach N,0 1 2 3 4,$(eval $(call hifive_timing_template,$(N))))

define hicpipe_timing_template
$(BASEDIR)/Analysis/Timing/hicpipe_%_$1.txt:
	@mkdir -p $(BASEDIR)/Analysis/Timing
	@export BASEDIR=$(BASEDIR)
	/usr/bin/time --verbose --output=$$@ $(BASEDIR)/Scripts/Timing/hicpipe_$$*.sh
endef
$(foreach N,0 1 2 3 4,$(eval $(call hicpipe_timing_template,$(N))))

define hicnorm_data_template
$(BASEDIR)/Analysis/Timing/hicnorm_data_$1.txt:
	@mkdir -p $(BASEDIR)/Analysis/Timing
	@echo "fend_fname='$(BASEDIR)/Data/Timing/hicpipe.fends'" > $(BASEDIR)/Scripts/Timing/hicnorm_data_$1.R
	@echo "mat_fname='$(BASEDIR)/Data/Timing/hicpipe.mat'" >> $(BASEDIR)/Scripts/Timing/hicnorm_data_$1.R
	@cat $(BASEDIR)/Scripts/Timing/hicnorm_data.R >> $(BASEDIR)/Scripts/Timing/hicnorm_data_$1.R
	/usr/bin/time --verbose --output=$$@ $(BASEDIR)/bin/Rscript --save $(BASEDIR)/Scripts/Timing/hicnorm_data_$1.sh
endef
$(foreach N,0 1 2 3 4,$(eval $(call hicnorm_data_template,$(N))))

define hicnorm_norm_template
$(BASEDIR)/Analysis/Timing/hicnorm_data_$1.txt:
	@mkdir -p $(BASEDIR)/Analysis/Timing
	@echo "out_fname='$(BASEDIR)/Data/Timing/hicnorm_heatmap.txt'" > $(BASEDIR)/Scripts/Timing/hicnorm_norm_$1.R
	@cat $(BASEDIR)/Scripts/Timing/hicnorm_norm.R >> $(BASEDIR)/Scripts/Timing/hicnorm_norm_$1.R
	/usr/bin/time --verbose --output=$$@ $(BASEDIR)/bin/Rscript --restore $(BASEDIR)/Scripts/Timing/hicnorm_norm_$1.sh
endef
$(foreach N,0 1 2 3 4,$(eval $(call hicnorm_norm_template,$(N))))

define hiclib_timing_template
$(BASEDIR)/Analysis/Timing/hiclib_%_$1.txt:
	@mkdir -p $(BASEDIR)/Analysis/Timing
	/usr/bin/time --verbose --output=$$@ python $(BASEDIR)/Scripts/Timing/hiclib_$$*.py $(BASEDIR)
endef
$(foreach N,0 1 2 3 4,$(eval $(call hiclib_timing_template,$(N))))

###########################################################################
# create subset data for NcoI mouse chromosome 1
###########################################################################
setup: $(foreach SRR,SRR443886 SRR443887 SRR443888,$(foreach STRAND,1 2,$(BASEDIR)/Data/Timing/$(SRR)_sub_$(STRAND).bam) \
	$(BASEDIR)/Data/Timing/mm9_NcoI_sub.fend $(BASEDIR)/Data/Timing/mm9_NcoI_sub.bed

$(BASEDIR)/Data/Timing/%_sub_1.bam:
	@mkdir -p $(BASEDIR)/Data/Timing
	$(BASEDIR)/bin/samtools view -h $(BASEDIR)/Data/HiC/Mapping/$*_1.bam > $(BASEDIR)/Data/Timing/$*_1.sam
	$(BASEDIR)/bin/samtools view -H $(BASEDIR)/Data/HiC/Mapping/$*_1.bam > $(BASEDIR)/Data/Timing/$*_sub_1.sam
	awk '$3 == 1' $(BASEDIR)/Data/Timing/$*_1.sam >> $(BASEDIR)/Data/Timing/$*_sub_1.sam
	samtools view -bS $(BASEDIR)/Data/Timing/$*_sub_1.sam > $(BASEDIR)/Data/Timing/$*_sub_1.bam
	ln -s $(BASEDIR)/Data/Timing/$*_sub_1.bam $(BASEDIR)/Data/Timing/$*_sub_1.bam.0

$(BASEDIR)/Data/Timing/%_sub_2.bam:
	@mkdir -p $(BASEDIR)/Data/Timing
	$(BASEDIR)/bin/samtools view -h $(BASEDIR)/Data/HiC/Mapping/$*_2.bam > $(BASEDIR)/Data/Timing/$*_2.sam
	$(BASEDIR)/bin/samtools view -H $(BASEDIR)/Data/HiC/Mapping/$*_2.bam > $(BASEDIR)/Data/Timing/$*_sub_2.sam
	awk '$3 == 1' $(BASEDIR)/Data/Timing/$*_2.sam >> $(BASEDIR)/Data/Timing/$*_sub_2.sam
	samtools view -bS $(BASEDIR)/Data/Timing/$*_sub_2.sam > $(BASEDIR)/Data/Timing/$*_sub_2.bam
	ln -s $(BASEDIR)/Data/Timing/$*_sub_2.bam $(BASEDIR)/Data/Timing/$*_sub_2.bam.0

$(BASEDIR)/Data/Timing/mm9_NcoI_sub.fend: $(BASEDIR)/Data/Genome/mm9_NcoI.fend
	@mkdir -p $(BASEDIR)/Data/Timing
	head -n 1 $^ > $@
	awk '$3 == 1' $^ >> $@

$(BASEDIR)/Data/Timing/mm9_NcoI_sub.bed: $(BASEDIR)/Data/Genome/mm9_NcoI.bed
	@mkdir -p $(BASEDIR)/Data/Timing
	head -n 1 $^ > $@
	awk '$1 == 1' $^ >> $@


.SECONDARY:
.PHONY: all correlations timing setup hifive_timing hicnorm_timing hicpipe_timing hiclib_timing